apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- namespace.yaml

namespace: monitoring

helmCharts:
- name: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  includeCRDs: true
  version: 6.46.0
  valuesFile: values.yaml
