apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doppler-operator-system

helmCharts:
- name: doppler-kubernetes-operator
  repo: https://helm.doppler.com
  includeCRDs: true
  version: 1.5.7
  valuesFile: values.yaml
