apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

namespace: longhorn-system

helmCharts:
- name: longhorn
  releaseName: longhorn
  repo: https://charts.longhorn.io
  includeCRDs: true
  version: 1.10.1
  namespace: longhorn-system
  valuesFile: values.yaml
    
patches:
  - path: tailscale.patch.yaml
    target:
      kind: Service
      name: longhorn-frontend
