apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

namespace: redpanda

helmCharts:
- name: redpanda
  repo: https://charts.redpanda.com
  releaseName: redpanda
  includeCRDs: true
  version: 25.3.2
  namespace: redpanda
  valuesFile: values.yaml
