apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ip-address-pool.yaml

namespace: metallb-system

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  includeCRDs: true
  version: v0.15.2
  namespace: metallb-system
  valuesFile: values.yaml
