apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

namespace: metallb

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  includeCRDs: true
  version: v0.15.2
  valuesFile: values.yaml
