apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
- name: amazon-eks-pod-identity-webhook
  repo: https://jkroepke.github.io/helm-charts/
  version: 2.5.6
  releaseName: amazon-eks-pod-identity-webhook
  namespace: kube-system
  valuesFile: values.yaml
