---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-clustersecretstore
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      secretsManager:
        forceDeleteWithoutRecovery: true
        # recoveryWindowInDays: 9 (conflicts with forceDeleteWithoutRecovery)
      auth:
        jwt:
          serviceAccountRef:
            namespace: external-secrets
            name: external-secrets
