---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 
  namespace: tailscale
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-clustersecretstore
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: dev/fomiller/homelab/tailscale-operator-creds
