apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: aws-eks-pod-identity-webook
  repo: https://jkroepke.github.io/helm-charts/
  version: 2.5.6
  releaseName: aws-eks-pod-identity-webook
  namespace: kube-system
  valuesFile: values.yaml
