apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml

helmGlobals:
  chartHome: ../../charts/
helmCharts:
- name: argo-cd
  releaseName: argocd
  includeCRDs: true
  valuesFile: values.yaml
